Replace ReSpec HTML drafts with Markdown versions
OCFL/spec pull request #596
Opened 2022-05-20 17:45 UTC by zimeon

Fixes #554

There is the following fixup required:

* in spec:
  * Indentation in example in 3.5.3.1 Version is not right: `empty.txt` and `empty2.txt` should be at some level
  * Non-normative notes that span multiple paragraphs need a tweak to avoid the quote bar having breaks in it
  * Adjust wrapping in RFC2119 reference so that the markdown doesn't incorrectly pick it up `1997.` as the start of a numbered list.
* in implementation notes:
  * In section 2.2, move examples to after the descriptions of Flat, PairTree and Truncated

If we have approval to go ahead (and commitment not to merge anything else in the meantime) that I can do these and get re-approval before merge. Must be careful to do a squash&merge

2022-05-20 18:09 UTC, neilsjefferies approved these changes

2022-05-21 17:58 UTC, awoods commented
Should we also remove: [respec-w3c-common.js](https://github.com/OCFL/spec/blob/main/draft/respec-w3c-common.js)?

2022-05-21 18:10 UTC, awoods commented
I am happy to move the current PR (which is fantastic) forward and then iterate on the refinements. Potential such refinements, in addition to those noted in the PR description:
1. The additional title at the top of the document seems unnecessary
2. Is there a way of having the 'table of contents' be in a side panel, so that it is always available.

Thanks!

2022-05-21 18:12 UTC, awoods requested changes
Approved, pending response minor comments.

2022-06-01 05:19 UTC, zimeon commented
> Should we also remove: [draft/respec-w3c-common.js](https://github.com/OCFL/spec/blob/main/draft/respec-w3c-common.js)?

Yes, done in https://github.com/OCFL/spec/pull/596/commits/bc8b159cae0581637b0d9d7cf70128b1e552f077

> I am happy to move the current PR (which is fantastic) forward and then iterate on the refinements. Potential such refinements, in addition to those noted in the PR description:
> 
> 1. The additional title at the top of the document seems unnecessary

We use this "extra" title (actually the `site.title`) on the homepage and news page. I have added into `_layouts/default.html` a check for an extra page variable `page.no_site_title` which can be used in the front matter to disable the extra title, this is added as `no_site_title: true` in both spec and implementation notes.

> 2. Is there a way of having the 'table of contents' be in a side panel, so that it is always available.

Yes, may take some work to get it right but this is the case for IIIF specs. See, e.g. https://iiif.io/api/presentation/3.0/

2022-06-01 14:32 UTC, zimeon commented on draft/implementation-notes/index.md
> +the \[[OCFL-Specification](#ref-ocfl-specification)\] is stored in the top level of the OCFL storage root. The OCFL
We perhaps need to write a style guide. For this PR I made things look like the ReSpec version

2022-06-03 11:36 UTC, awoods approved these changes

2022-06-03 11:37 UTC, merged