Replicate specification of Object extension section
OCFL/spec pull request #607
Opened 2022-06-22 02:11 UTC by awoods

This update replicates the Object extension specification text from Object extension into Storage Root extension

Resolves: #557

Supersedes: https://github.com/OCFL/spec/pull/583

2022-06-22 17:10 UTC, rosy1280 reviewed
@awoods leaving a comment because i'm not sure this is a hold up for approval.  would rather others weight in.

2022-06-22 17:10 UTC, rosy1280 commented on draft/spec/index.md
> +The `extensions` directory <span id="E112" class="rfc2119">MUST NOT</span> contain any files, and no sub-directories
This sentence is awkward.  Why not:

> The `extensions` directory MUST NOT contain any files or subdirectories other than extension subdirectories...

2022-06-22 18:05 UTC, zimeon requested changes

2022-06-22 18:05 UTC, zimeon commented on draft/spec/index.md
> +> Non-normative note: Extension sub-directories should use the same name as a registered extension in order to both
Can we run the two non-normative notes (this and the existing one that follows) into one? I.e. put a `>` for the blank line between paras and remove the second "Non-normative note: "

2022-06-22 18:05 UTC, zimeon commented on draft/spec/index.md
> +> Non-normative note: Extension sub-directories should use the same name as a registered extension in order to both
(otherwise looks good)

2022-06-23 07:15 UTC, julianmorley approved these changes

2022-06-23 07:15 UTC, merged