Reword filesystem case sensitivity requirement
OCFL/spec pull request #641
Opened 2023-09-23 14:12 UTC by zimeon

Fixes #528

2023-09-23 17:41 UTC, neilsjefferies approved these changes

2023-10-30 19:49 UTC, rosy1280 approved these changes

2023-11-05 21:32 UTC, awoods requested changes
The change looks good. In order to flag this change as one that impacts (reduces) the `MUST`s, it may be helpful to add that fact to the pull-request description... so that it shows up in the release notes.

2024-02-01 16:52 UTC, zimeon commented
@awoods - I amended the description to note that a MUST is removed

2024-02-01 17:07 UTC, awoods approved these changes

2024-02-01 17:07 UTC, merged